spring:
  application:
    name: bartofinance-backend
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/bartofinance
      # Para MongoDB Atlas (cloud), use o formato:
      # uri: mongodb+srv://<username>:<password>@cluster.mongodb.net/bartofinance?retryWrites=true&w=majority
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: America/Sao_Paulo

server:
  port: 8080
  address: 0.0.0.0 # Aceita conexões de qualquer IP
  error:
    include-message: always
    include-binding-errors: always

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:BartoFinanceSecretKeyForJWTTokenGenerationAndValidation2024MustBeAtLeast256BitsLong}
  expiration: 86400000 # 24 horas em millisegundos

# Logging Configuration
logging:
  level:
    root: INFO
    com.bartofinance: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/bartofinance.log

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

